btagWeightCategory = ["1","(1-btagWeight[0])","(btagWeight[2])","(btagWeight[1])"]

def GetHistogramInfo(extraCuts, extraPhotonCuts, nBJets):

    histogramInfo = [ ["jetPt[0]"  , "presel_jet1Pt"   ,    [1000,0,1000], extraCuts      , "", True],
                      ["jetPt[1]"  , "presel_jet2Pt"   ,      [600,0,600], extraCuts      , "", True],
                      ["jetPt[2]"  , "presel_jet3Pt"   ,      [600,0,600], extraCuts      , "", True],
                      ["nJet"      , "presel_Njet"     ,        [15,0,15], extraCuts      , "", True],
                      ["nBJet"     , "presel_Nbjet"    ,        [10,0,10], extraCuts      , "", True],
                      ["muPt"      , "presel_muPt"     ,      [600,0,600], extraCuts      , "", True],
                      ["muEta"     , "presel_muEta"    ,   [100,-2.4,2.4], extraCuts      , "", True],
                      ["muPhi"     , "presel_muPhi"    , [100,-3.15,3.15], extraCuts      , "", True],
                      ["elePt"     , "presel_elePt"    ,      [600,0,600], extraCuts      , "", True],
                      ["eleSCEta"  , "presel_eleSCEta" ,   [100,-2.4,2.4], extraCuts      , "", True],
                      ["elePhi"    , "presel_elePhi"   , [100,-3.15,3.15], extraCuts      , "", True],
                      ["M3"        , "presel_M3"       ,      [300,0,600], extraCuts      , "", True],
                      ["pfMET"     , "presel_MET"      ,      [300,0,600], extraCuts      , "", True],
                      ["pfMETPhi"  , "presel_METPhi"   , [100,-3.15,3.15], extraCuts      , "", True],
                      ["nVtx"      , "presel_nVtx"     ,        [50,0,50], extraCuts      , "", True],
                      ["WtransMass","presel_WtransMass",       [80,0,400], extraCuts      , "", True],
                      ["HT"        ,"presel_HT"        ,   [150,120,1500], extraCuts      , "", True],
                      ["nVtx"      , "presel_nVtxup"   ,        [50,0,50], extraCuts      , "%sevtWeight*PUweight_Up*muEffWeight*eleEffWeight*%s"%(extraCuts,btagWeightCategory[nBJets]), False],
                      ["nVtx"      , "presel_nVtxdo"   ,        [50,0,50], extraCuts      , "%sevtWeight*PUweight_Do*muEffWeight*eleEffWeight*%s"%(extraCuts,btagWeightCategory[nBJets]), False],
                      ["nVtx"      , "presel_nVtxNoPU" ,        [50,0,50], extraCuts      , "%sevtWeight*muEffWeight*eleEffWeight*%s"%(extraCuts,btagWeightCategory[nBJets]), False],
                      ["nVtx"      , "phosel_nVtxup"   ,        [50,0,50], extraPhotonCuts%("phoMediumID"), "%sevtWeight*PUweight_Up*muEffWeight*eleEffWeight*%s"%(extraPhotonCuts%("phoMediumID"),btagWeightCategory[nBJets]), False],
                      ["nVtx"      , "phosel_nVtxdo"   ,        [50,0,50], extraPhotonCuts%("phoMediumID"), "%sevtWeight*PUweight_Do*muEffWeight*eleEffWeight*%s"%(extraPhotonCuts%("phoMediumID"),btagWeightCategory[nBJets]), False],
                      ["nVtx"      , "phosel_nVtxNoPU" ,        [50,0,50], extraPhotonCuts%("phoMediumID"), "%sevtWeight*muEffWeight*eleEffWeight*%s"%(extraPhotonCuts%("phoMediumID"),btagWeightCategory[nBJets]), False],
                      ["nVtx"      , "phosel_nVtx"     ,        [50,0,50], extraPhotonCuts%("phoMediumID") , "", True],
    #		  ["DiphoMass"     , "phosel_DiphoMass"                     ,       [80,0,400], extraPhotonCuts%("phoMediumID"), "", True],
                      ["nPho"          , "phosel_Nphotons"                      ,          [3,1,4], extraPhotonCuts%("phoMediumID"), "", True],
                      ["phoEt[0]"      , "phosel_LeadingPhotonEt"               ,      [300,0,300], extraPhotonCuts%("phoMediumID"), "", True],
                      ["phoEt[1]"      , "phosel_SecondLeadingPhotonEt"         ,      [300,0,300], extraPhotonCuts%("phoMediumID"), "", True],
                      ["phoEta[0]"     , "phosel_LeadingPhotonEta"              ,    [50,-2.5,2.5], extraPhotonCuts%("phoMediumID"), "", True],
                      ["phoSCEta[0]"   , "phosel_LeadingPhotonSCEta"            ,    [50,-2.5,2.5], extraPhotonCuts%("phoMediumID"), "", True],
                      ["dRPhotonJet[0]"   , "phosel_dRLeadingPhotonJet"            ,        [200,0,5], extraPhotonCuts%("phoMediumID"), "", True],
                      ["dRPhotonJet[0]"   , "phosel_dRLeadingPromptPhotonJet"      ,        [200,0,5], extraPhotonCuts%("phoMediumID && (photonIsGenuine||photonIsMisIDEle)"), "", False],
                      ["dRPhotonJet[0]"   , "phosel_dRLeadingNonPromptPhotonJet"   ,        [200,0,5], extraPhotonCuts%("phoMediumID && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", False],
                      ["dRPhotonLepton[0]", "phosel_dRLeadingPromptPhotonLepton"   ,        [120,0,6], extraPhotonCuts%("phoMediumID && (photonIsGenuine||photonIsMisIDEle)"), "", False],
                      ["dRPhotonLepton[0]", "phosel_dRLeadingNonPromptPhotonLepton",        [120,0,6], extraPhotonCuts%("phoMediumID && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", False],
                      ["dRPhotonLepton[0]", "phosel_dRLeadingGenuinePhotonLepton"  ,        [120,0,6], extraPhotonCuts%("phoMediumID && photonIsGenuine"),"", False],
                      ["dRPhotonLepton[0]", "phosel_dRLeadingMisIDEleLepton"       ,        [120,0,6], extraPhotonCuts%("phoMediumID && photonIsMisIDEle"),"", False],
                      ["dRPhotonLepton[0]", "phosel_dRLeadingHadPhoLepton"         ,        [120,0,6], extraPhotonCuts%("phoMediumID && photonIsHadronicPhoton"),"", False],
                      ["dRPhotonLepton[0]", "phosel_dRLeadingHadFakeLepton"        ,        [120,0,6], extraPhotonCuts%("phoMediumID && photonIsHadronicFake"),"", False],
                      ["dRPhotonLepton[0]", "phosel_dRLeadingPhotonLepton"         ,        [120,0,6], extraPhotonCuts%("phoMediumID"), "", True],
                      ["WtransMass"    , "phosel_WtransMass"      ,      [80,0,400], extraPhotonCuts%("phoMediumID"), "", True],		
                      ["HT"            , "phosel_HT"              ,  [150,120,1500], extraPhotonCuts%("phoMediumID"), "", True],
                      ["M3"            , "phosel_M3"              ,     [300,0,600], extraPhotonCuts%("phoMediumID"), "", True],
                      ["M3"            , "phosel_M3_GenuinePho"   ,     [300,0,600], extraPhotonCuts%("phoMediumID && photonIsGenuine")       , "", False],
                      ["M3"            , "phosel_M3_MisIDEle"     ,     [300,0,600], extraPhotonCuts%("phoMediumID && photonIsMisIDEle")      , "", False],
                      ["M3"            , "phosel_M3_HadronicPho"  ,     [300,0,600], extraPhotonCuts%("phoMediumID && photonIsHadronicPhoton"), "", False],
                      ["M3"            , "phosel_M3_HadronicFake" ,     [300,0,600], extraPhotonCuts%("phoMediumID && photonIsHadronicFake")  , "", False],
                      ["pfMET"         , "phosel_MET"             ,     [300,0,600], extraPhotonCuts%("phoMediumID"), "", True],
                      ["elePt"         , "phosel_elePt"           ,     [600,0,600], extraPhotonCuts%("phoMediumID"), "", True],
                      ["eleSCEta"      , "phosel_eleSCEta"        ,  [100,-2.4,2.4], extraPhotonCuts%("phoMediumID"), "", True],
                      ["muPt"          , "phosel_muPt"            ,     [600,0,600], extraPhotonCuts%("phoMediumID"), "", True],
                      ["muEta"         , "phosel_muEta"           ,  [100,-2.4,2.4], extraPhotonCuts%("phoMediumID"), "", True],
                      ["nJet"          , "phosel_Njet"            ,       [15,0,15], extraPhotonCuts%("phoMediumID"), "", True],
                      ["nBJet"         , "phosel_Nbjet"           ,       [10,0,10], extraPhotonCuts%("phoMediumID"), "", True],
                      ["phoHoverE"     , "phosel_HoverE"          ,    [100,0.,.04], extraPhotonCuts%("phoMediumID"), "", True],
                      ["phoSIEIE"      , "phosel_SIEIE"           ,    [100,0.,.03], extraPhotonCuts%("phoMediumID"), "", True],
                      ["phoPFChIso"    , "phosel_ChIso"           ,      [100,0,.5], extraPhotonCuts%("phoMediumID"), "", True],
                      ["phoPFNeuIso"   , "phosel_NeuIso"          ,      [100,0,5.], extraPhotonCuts%("phoMediumID"), "", True],
                      ["phoPFPhoIso"   , "phosel_PhoIso"          ,        [50,0,5], extraPhotonCuts%("phoMediumID"), "", True],
                      ###############
                      ["loosePhoHoverE"  , "phosel_noCut_HoverE"               ,      [100,0.,.2], extraPhotonCuts%("loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso"), "", True],
                      ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_barrel"         ,    [100,0.,.015], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && (abs(loosePhoSCEta)<1.47)"),"", True],
                      ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_endcap"         ,  [100,0.015,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && (abs(loosePhoSCEta)>1.47)"),"", True],
                      ["loosePhoSIEIE"   , "phosel_noCut_SIEIE"                ,     [100,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso"), "", True],
                      ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_GenuinePho"     ,     [100,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsGenuine"), "", False],
                      ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_MisIDEle"       ,     [100,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsMisIDEle"), "", False],
                      ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_HadPho"         ,     [100,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicPhoton"), "", False],
                      ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_HadFake"        ,     [100,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicFake"), "", False],
                      ["loosePhoPFChIso" , "phosel_noCut_ChIso"                ,        [80,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso"), "", True],
                      ["loosePhoPFChIso" , "phosel_noCut_ChIso_GenuinePhoton"  ,        [80,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsGenuine"), "", False],
                      ["loosePhoPFChIso" , "phosel_noCut_ChIso_MisIDEle"       ,        [80,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsMisIDEle"), "", False],
                      ["loosePhoPFChIso" , "phosel_noCut_ChIso_HadronicPhoton" ,        [80,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicPhoton"), "", False],
                      ["loosePhoPFChIso" , "phosel_noCut_ChIso_HadronicFake"   ,        [80,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicFake"), "", False],
                      ["loosePhoPFChIso" , "phosel_noCut_ChIso_PromptPhoton"   ,        [80,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && (loosePhotonIsGenuine||loosePhotonIsMisIDEle)")           , "", False],
                      ["loosePhoPFChIso" , "phosel_noCut_ChIso_NonPromptPhoton",        [80,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && (loosePhotonIsHadronicPhoton||loosePhotonIsHadronicFake)"), "", False],
                      ["loosePhoPFNeuIso", "phosel_noCut_NeuIso"               ,        [80,0,40], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassPhoIso")                                 , "", True],
                      ["loosePhoPFPhoIso", "phosel_noCut_PhoIso"               ,      [200,0,100], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso")                                 , "", True],
                      ["loosePhoPFChIso" , "phosel_AntiSIEIE_ChIso"            ,        [80,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && !loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso")                               , "", True],
                      ["loosePhoPFChIso" , "phosel_AntiSIEIE_ChIso_GenuinePho" ,        [80,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && !loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsGenuine")       , "", False],
                      ["loosePhoPFChIso" , "phosel_AntiSIEIE_ChIso_MisIDEle"   ,        [80,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && !loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsMisIDEle")      , "", False],
                      ["loosePhoPFChIso" , "phosel_AntiSIEIE_ChIso_HadPho"     ,        [80,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && !loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicPhoton"), "", False],
                      ["loosePhoPFChIso" , "phosel_AntiSIEIE_ChIso_HadFake"    ,       [200,0,50], extraPhotonCuts%("loosePhoMediumIDPassHoverE && !loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicFake")  , "", False],
                      #################
                      ["nPho"              , "phosel_NGenuinePho"       ,          [2,0,2], extraPhotonCuts%("photonIsGenuine")                       , "", False],
                      ["nPho"              , "phosel_NMisIDEle"         ,          [2,0,2], extraPhotonCuts%("photonIsMisIDEle")                      , "", False],
                      ["nPho"              , "phosel_NHadronicPho"      ,          [2,0,2], extraPhotonCuts%("photonIsHadronicPhoton")                , "", False],
                      ["nPho"              , "phosel_NHadronicFake"     ,          [2,0,2], extraPhotonCuts%("photonIsHadronicFake")                  , "", False],
                      ["phoPFRandConeChIso", "phosel_RandomCone"        ,        [80,0,20], extraPhotonCuts%("phoMediumID")                           , "", False],
                      ["photonParentPID"   , "phosel_mcMomPIDGenuinePho",[2000,-1000,1000], extraPhotonCuts%("phoMediumID && photonIsGenuine")        , "", False],
                      ["photonParentPID"   , "phosel_mcMomPIDMisIDEle"  ,[2000,-1000,1000], extraPhotonCuts%("phoMediumID && photonIsMisIDEle")       , "", False],
                      ["photonParentPID"   , "phosel_mcMomPIDHadPho"    ,[2000,-1000,1000], extraPhotonCuts%("phoMediumID && photonIsHadronicPhoton") , "", False],
                      ["photonParentPID"   , "phosel_mcMomPIDHadFake"   ,[2000,-1000,1000], extraPhotonCuts%("phoMediumID && photonIsHadronicFake")   , "", False],
                      ]
    return histogramInfo
